### ISSUE TITLE
Count me in!

### ISSUE THREAD

**Issue by andylokandy** [dcao/elba#1]
I'm really interested in implementing a package manager for idris, esspecially given that it's written in rust.

I have plenty of experience with rust and idris, but I don't have any knowledge in implementing a package manager.

Would you recommend some reading material or source code for me to get started?

Also, could you write down the implement status and roadmap? Imo, the implementation detail would be much useful for me and the other contributors to get invoved.

**Comment by dcao** [comment]
Thanks for your enthusiasm and interest! Package management is a pretty big problem, and it's always great to have more help at the helm (especially with your experience with both of the relevant languages of this task) to help conquer this beast.

For now, my main priority is to get the basic functions of `elba` working and kick out a minimum viable product, so it might take me a little bit of time to write up the implementation status & roadmap for the tool. Plus, a lot of code is undocumented, so I'll have to clean up after myself there. I'm guessing I should be able to have the former up in a week or so, but that isn't a hard deadline.

If you're looking for relevant reading material for package managers, I'd highly suggest the source code of cargo (and maybe some of the RFCs surrounding its development) since `elba` is very strongly influenced by cargo and cargo's code is pretty clear and contains several nuggets of information in documentation. Dart's Pub also has some very helpful pieces of documentation, including its [article on its versioning philosophy](https://www.dartlang.org/tools/pub/versioning) and its [documentation on the Pubgrub version solving algorithm](https://github.com/dart-lang/pub/blob/master/doc/solver.md), which `elba` uses. `elba`'s own source code also has some info on its design decisions, mainly with regard to package indices (caches of package metadata), which is in the relevant module documentation.

**Comment by andylokandy** [comment]
I finished reading the documentation of Pubgrub and read most `elba`'s source code. AFAICS, you have done the most part of versioning, dependencies resolving and caching, while we need more work on command line parsing, networking and compiling. Well done!

The structure of `elba` largely differs from the one of `cargo`. I understand that this is because of the reasons for simplification. If that is the case, I think we could ignore the third-party registry and the caching matters first, in this way we can push forward to a runnable version more quickly. Of course, you need some time to settle down the design of structure, so implementing these in advance may be good choice either.

I think I can get started right now on the building(compiler binding) or the command line interface, which does not involve package manager knowledge. Should I? Which one is better?

**Comment by andylokandy** [comment]
And I have some concerns about the current design, which may be naive or not worth discussing in this stage. I just write them down as memo. You don't have to explain them if you think you have good reasons.

- **Package namespacing**

  Namespacing is long discussed in rust community, [here](https://internals.rust-lang.org/t/crates-io-package-policies/1041) is the conclusion(one of the sections).

> While namespaced packages allow multiple authors to use a single, generic name, they add complexity to how packaged are referenced in Rust code and in human communication about packages. At first glance, they allow multiple authors to claim names like http, but that simply means that people will need to refer to those packages as wycats' http or reem's http, offering little benefit over package names like wycats-http or reem-http.

> When we looked at package ecosystems without namespacing, we found that people tended to go with more creative names (like nokogiri instead of “tenderlove’s libxml2”). These creative names tend to be short and memorable, in part because of the lack of any hierarchy. They make it easier to communicate concisely and unambiguously about packages. They create exciting brands. And we’ve seen the success of several 10,000+ package ecosystems like NPM and RubyGems whose communities are prospering within a single namespace.

- **Cache file name**

  Cache file is named after "group_name-hash" so far. I think adding the version, like "group_name-1.0.0-hash", would be more ergonomic.

- **Version with band**

  Now the versions can go with a bang to allow pre-release version(if I didn't get it wrong), which appears in neither Cargo nor Pub. IMO, it casused unessesary complexity for users, esspecially for the ones who don't use this feature to read other's code . Pre-released packages can be referd more explicitly like "foo = "1.0.0-alpha"", and prefer to chose the stable one if not designated.

- **Multiple exports for lib**

  Multiple exports means automatically merging several idr into a single lib file. It can lead to less explicitness of lib structure because you can't figure out the library interface only by reading a single lib.idr, but you need to read the manifest and all the lib files invovled, and you have to rememeber some conventions of how to mix up contents of mutiple files. Also, the mixin may cause confliction when compiling.

**Comment by dcao** [comment]
I think a good first place to start would be writing a Rust interface to the Idris compiler (a builder struct which creates an invocation to the Idris compiler). After that, we can start working on actually building Idris packages and throwing them into the cache directory.

<hr />

I think it's worth having a discussion about these issues now since committing to a faulty design might lead to unending pain and sorrow in the future :). So to address your concerns:
- **Package namespacing**
I was reading through that thread too when I was mulling whether to add support for namespaced packages, and I eventually decided on mandating namespaces for a few reasons:
  - Ad-hoc namespacing with hyphens or underscores, as suggested by a few people in that thread, can be misleading since then anybody would be able to publish a package that starts with another "namespace" and feign credibility, even if it isn't there (hypothetically, I could publish a `wycats-log` package, etc. on crates.io).
  - Nothing is stopping people from having their creative names alongside namespaces. Github has namespaced repositories, yet I didn't name this project `dcao/package_manager`. Namespacing just gives people the option to use less interesting names when it suits the project or makes things more clear.
  - Namespacing prevents problems like the `kik` package on npm from happening; now we have `dcao/kik` or `andylokandy/kik` to disambiguate.
- **Cached source directory names**
That's not a bad suggestion; it might make the directory a little bit longer, but that's not a big deal. My only real qualm is that for something like a git repository, the version is irrelevant, so we'd have to check that in the code (which might make it a little more complicated, but this isn't a big deal).
- **`!` versions**
Originally, these were meant as an implementation detail, since the Pubgrub resolution algorithm requires us to take the complement and difference between different sets of Constraints (the complement of `≥ 1.0.0` should include all pre-releases of 1.0.0, hence `<! 1.0.0`). In Dart, `<! 1.0.0` is represented as `< 1.0.0-∞`, and `≥! 1.0.0` is equivalent to `≥ 1.0.0-0`, but this syntax seemed a bit weird and prone to error to me (if a character has a higher unicode value than infinity, is it a larger version?), so I decided to go with `<!` and `≥!`. I also didn't want to keep this as magic functionality exclusively reserved to the package manager, since it might be useful in some circumstances, so I just added it to the parser as well.
- **Multiple exports for libraries**
I was just intending the exports to be like the modules field in present-day [ipkg files](http://docs.idris-lang.org/en/latest/tutorial/packages.html) - whichever modules were listed would be copied into the build directory for use by others. I guess this is unnecessary for our purposes, (we should just copy everything from the src/ dir or wherever the lib directory is located), so I'll modify that.

**Comment by andylokandy** [comment]
- **Package namespacing**

  Alright, you got me. But there is still a technical problem that how dose Idris language interact with namespace. Consider we have two parser libary: 'andylokandy/parser' and 'dcao/parser'.

In my project, I may use both of the parser libary.

```
// Elba.toml

[dependencies]
andylokandy/parser = "0.1"
dcao/parser = "0.1"
```

```idris
-- Main.idr

import Parser
-- And then? How to import the other one?
```

- **Cached source directory names**
  No, it's not a big deal, and I'm not sure how users will interact with cache files, so I prefer keeping it untouched for now.

**Comment by dcao** [comment]
I think w.r.t. namespace conflicts, we could just require that the root module be the namespace, so you'd have `import Andylokandy.Parser` instead of just `import Parser`.
