### ISSUE TITLE
Replace DirLock with flock

### ISSUE THREAD

**Issue by andylokandy** [dcao/elba#10]
Currently, elba refuses to work and complians of the dir lock if the previous run is forced canceled. So I'm trying to replace the current DirLock strategy with file lock provided by [fs2](https://crates.io/crates/fs2). Besides, by using flock we can blocking wait on the file instead of crash the process immediately.

**Comment by dcao** [comment]
I'd still like to having locks on whole directories rather than having to go through individual files and lock every single one in the directory to make sure that nobody else is touching it, so I think for an implementation we could still use `folder_name.lock` files to track directory locks, but instead of using the presence of the file as the lock, we use an fs2 lock.

If this sounds okay to you I can implement it, since it's a pretty small change.

**Comment by andylokandy** [comment]
Sounds good.

**Comment by andylokandy** [comment]
Is that better if we place the lockfile in the directory? It prevents the current outer folder pollution and should be more ergonomic(pleasing) for users. And we can unify the lockerfile name like `.elbalock`, `.dirlock` or whatever.

**Comment by andylokandy** [comment]
No matter where we put the file, we have better check whether the size equals to zero, to avoid unexpected collision.
